name: spacebridge

channels:
  - conda-forge

dependencies:
  - pip=21.3.1
  - ploomber=0.13.3
  - pygraphviz
  - numpy=1.22.0
  - matplotlib=3.4.3
  - scipy=1.5.3
  - xarray=0.19.0
  - tensorflow=2.6.0
  - tensorboard=2.6.0
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - imageio=2.9.0
  - scikit-image=0.18.3
  - scikit-learn=0.23.2
  - pathlib=1.0.1
  - jupyter
  - jupyterlab=3.2.1
  - jupyterlab-git=0.33.0
  - jupyterlab-variableinspector=3.0.9
  - mamba_gator=5.1.2
  - nodejs=16.11.1
  - cartopy=0.20.1
  - netCDF4=1.5.7
  - h5netcdf=0.13.0
  - salem=0.3.7
  - pycaret=2.3.6
  - pip:
    - pytest
    - tensorflow-gpu==2.6.0
    - opencv-python==4.5.4.58
